#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Mac-Glue-Apps-AddressBookExport
version:      0.1
version_from: lib/Mac/Glue/Apps/AddressBookExport.pm
installdirs:  site
requires:
    Text::vCard:                   1.9
    Encode:                        0.1
    Template:                      2
    Mac::Glue:                     1.22
    Test::More:                    0.1

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
